org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.241
neo_version_range=[21,)
loader_version_range=[4,)
mod_id=game_console
mod_name=Game Console
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.wzz.game_console
mod_authors=Barbatosishere
mod_description=Game Console - A mod with 30+ mini games
